version: '3.10.7'
services: 
  web:
    build: .

    working_dir: /app

    command: python manage.py runserver 0.0.0.0:80

    volumes:
      - ./app

    ports:
      - 80:80 
    
    
    depends_on:
      - db

  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgres/data/
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=project_database
volumes:
  postgres_data:




